# The Site Configuration

# Import the theme
theme: jekyll-theme-chirpy

# The language of the webpage
lang:

# Change to your timezone
timezone: Asia/Seoul

# jekyll-seo-tag settings
# ↓ --------------------------

title: Jabcho # the main title

tagline: Jabcho's documentation space # it will display as the subtitle

description: >-
  A minimal, responsive and feature-rich Jekyll theme for technical writing.

# Fill in the protocol & hostname for your site.
url: "https://jabcho.github.io"

github:
  username: jabcho

social:
  name: jabcho
  email: yunsuu0220@gmail.com
  links:
    - https://github.com/jabcho

webmaster_verifications:
  google:
  bing:
  alexa:
  yandex:
  baidu:
  facebook:

# ↑ --------------------------
# The end of `jekyll-seo-tag` settings

# Web Analytics Settings
analytics:
  google:
    id:
  goatcounter:
    id:
  umami:
    id:
    domain:
  matomo:
    id:
    domain:
  cloudflare:
    id:
  fathom:
    id:

# Page views settings
pageviews:
  provider:

# Prefer color scheme
theme_mode:

# CDN for media
cdn:

# avatar on sidebar
avatar: "/assets/img/favicons/web-app-manifest-512x512.png"

# site-wide social preview
social_preview_image:

# global TOC in posts
toc: true

comments:
  provider: utterances
  disqus:
    shortname:
  utterances:
    repo: Jabcho/Jabcho.github.io
    issue_term: pathname
  giscus:
    repo:
    repo_id:
    category:
    category_id:
    mapping:
    strict:
    input_position:
    lang:
    reactions_enabled:

assets:
  self_host:
    enabled:
    env:

pwa:
  enabled: true
  cache:
    enabled: true
    deny_paths:

# paginate: 10
plugins: # /blog/하위로 들어가도록 plugin 추가
  - jekyll-paginate-v2

paginate: null
paginate_path: null

pagination: # [추가] v2 설정
  enabled: true
  per_page: 10
  permalink: "/blog/page/:num/"
  sort_field: "date"
  sort_reverse: true

# The base URL of your site
baseurl: ""

# ------------ The following options are not recommended to be modified ------------------

kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# === CHANGED: collections에 apis 추가 ===
collections:
  tabs:
    output: true
    sort_by: order
  apis: # ← ADDED: API 문서 컬렉션
    output: true
    permalink: /api/:path/
    sort_by: nav_order # ← ADDED: 사이드바 정렬 기준

# === CHANGED: defaults에 apis 전용 값 추가 ===
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      toc: true
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/
  - scope: # ← ADDED: apis 컬렉션 공통값
      path: ""
      type: apis
    values:
      layout: api_doc # _layouts/api_doc.html (6단계에서 생성)
      comments: true
      toc: true

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - purgecss.js
  - "*.config.js"
  - "package*.json"
  - .scratch/

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/

livereload: true
watch: true
